export const ORDERS_ERRORS = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ACCESS_DENIED: 'ACCESS_DENIED',
  DRIVER_NOT_ASSIGNED: 'DRIVER_NOT_ASSIGNED',
  ORDER_NOT_PENDING: 'ORDER_NOT_PENDING',
  ORDER_NOT_PLACED: 'ORDER_NOT_PLACED',
  ORDER_CANNOT_BE_CANCELLED: 'ORDER_CANNOT_BE_CANCELLED',
  CANNOT_REPORT_PROBLEM_IN_CURRENT_STATUS:
    'CANNOT_REPORT_PROBLEM_IN_CURRENT_STATUS',
  NOT_ASSIGNED_TO_THIS_ORDER: 'NOT_ASSIGNED_TO_THIS_ORDER',
  CANNOT_ASSIGN_DRIVER_TO_CLOSED_ORDER: 'CANNOT_ASSIGN_DRIVER_TO_CLOSED_ORDER',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_PROFILE_NOT_INITIALIZED: 'DRIVER_PROFILE_NOT_INITIALIZED',
  DRIVER_IS_BEING_ASSIGNED_ANOTHER_ORDER:
    'DRIVER_IS_BEING_ASSIGNED_ANOTHER_ORDER',
  DRIVER_MAX_DEBT_EXCEEDED: 'DRIVER_MAX_DEBT_EXCEEDED',
  COMMISSION_ALREADY_APPLIED: 'COMMISSION_ALREADY_APPLIED',
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
  ORDER_NOT_ACCEPTED_BY_DRIVER: 'ORDER_NOT_ACCEPTED_BY_DRIVER',
  ORDER_NOT_READY_YET: 'ORDER_NOT_READY_YET',
  NOT_COD_ORDER: 'NOT_COD_ORDER',
  CASH_NOT_REPORTED: 'CASH_NOT_REPORTED',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  NO_CASH_CONFIRMATIONS: 'NO_CASH_CONFIRMATIONS',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  NOT_YOUR_ORDER: 'NOT_YOUR_ORDER',
  ORDER_NOT_DELIVERED_YET: 'ORDER_NOT_DELIVERED_YET',
  NOT_A_WALLET_ORDER: 'NOT_A_WALLET_ORDER',
  NO_HELD_BALANCE_OR_ALREADY_PROCESSED: 'NO_HELD_BALANCE_OR_ALREADY_PROCESSED',
  DISPUTE_ALREADY_EXISTS: 'DISPUTE_ALREADY_EXISTS',
  VENDOR_CLOSED: 'VENDOR_CLOSED',
  SUBSCRIPTION_ORDER_LIMIT_REACHED: 'SUBSCRIPTION_ORDER_LIMIT_REACHED',
  ORDER_NOT_SHIPPED: 'ORDER_NOT_SHIPPED',
  INVALID_DELIVERY_OTP: 'INVALID_DELIVERY_OTP',
  OTP_REQUIRED: 'OTP_REQUIRED',
  INVALID_COUPON_CODE: 'INVALID_COUPON_CODE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  DRIVER_BUSY: 'DRIVER_BUSY',
  DRIVER_OFFLINE: 'DRIVER_OFFLINE',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
} as const;

export const ORDERS_NOTIFICATIONS = {
  CONFIRM_DELIVERY: 'notification_template_confirm_delivery',
  ORDER_COMPLETED: 'notification_template_order_completed',
  ORDER_CANCELLED: 'notification_template_order_cancelled',
  ORDER_FAILED_DELIVERY: 'notification_template_order_failed_delivery',
  ORDER_FAILED_DELIVERY_VENDOR:
    'notification_template_order_failed_delivery_vendor',
  MANAGER_DRIVER_REJECTED: 'notification_template_manager_driver_rejected',
  MANAGER_DRIVER_ACCEPTED: 'notification_template_manager_driver_accepted',
  ORDER_REJECTED: 'notification_template_order_rejected',
  ORDER_ACCEPTED: 'notification_template_order_accepted',
  ORDER_SHIPPED: 'notification_template_order_shipped',
  ORDER_PLACED: 'notification_template_order_placed',
  ORDER_READY: 'notification_template_order_ready',
  ORDER_IN_TRANSIT: 'notification_template_order_in_transit',
  ORDER_DRIVER_PENDING: 'notification_template_order_driver_pending',
  ORDER_DRIVER_ACCEPTED: 'notification_template_order_driver_accepted',
  ORDER_AUTO_CANCELLED: 'notification_template_order_auto_cancelled',
  MANAGER_ORDER_READY: 'notification_template_manager_order_ready',
  MANAGER_ORDER_AUTO_CANCELLED:
    'notification_template_manager_order_auto_cancelled',
} as const;

export enum NotificationEventType {
  DISPUTE_CREATED = 'DISPUTE_CREATED',
  DELIVERY_ISSUE = 'DELIVERY_ISSUE',
}

export enum AnalyticsEventType {
  ORDER_CREATED = 'ORDER_CREATED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_REJECTED = 'DRIVER_REJECTED',
  VENDOR_REJECTED = 'VENDOR_REJECTED',
  VENDOR_ACCEPTED = 'VENDOR_ACCEPTED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_PREPARED = 'ORDER_PREPARED',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_IN_TRANSIT = 'ORDER_IN_TRANSIT',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
}

export const OrderConstants = {
  REDIS_LOCK_ASSIGN_ORDER_PREFIX: 'lock:assign_order:',
  DRIVER_TRANSACTION_USER: 'driver',
  CUSTOMER_TRANSACTION_USER: 'customer',
  WALLET_OPERATION_ADD: 'add',
  WALLET_OPERATION_SUBTRACT: 'subtract',
  HELD_BALANCE_REASON_AWAITING_CONFIRMATION: 'awaiting_delivery_confirmation',
  MANAGER_AUDIT_ACTION_DISPATCH: 'dispatch',
  SYSTEM_ACTOR_ID: 'system',
} as const;

export const OrderSocketEvents = {
  // Room prefixes
  ZONE_ROOM_PREFIX: 'zone_',
  VENDOR_ROOM_PREFIX: 'vendor_',

  // Server events
  ORDER_UPDATED: 'orderUpdated',
  VENDOR_ORDER_UPDATED: 'vendorOrderUpdated',
  CUSTOMER_ORDER_UPDATED: 'customerOrderUpdated',
  DRIVER_ORDER_UPDATED: 'driverOrderUpdated',
  ZONE_ORDER_UPDATED: 'zoneOrderUpdated',
  DRIVER_LOCATION_UPDATED: 'orderDriverLocationUpdated',
  JOIN_ORDERS_ROOM: 'joinOrdersRoom',
  LEAVE_ORDERS_ROOM: 'leaveOrdersRoom',
} as const;
